# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: install dependencies
          command: |
            eval "$(pyenv init -)"
            pyenv shell 3.5.2
            python -m venv venv
            . venv/bin/activate
            pip install sregistry[all]
            chmod u+x ~/repo/.circleci/*.sh
            /bin/bash ~/repo/.circleci/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies
        
      - run:
          name: build container
          command: |
            . venv/bin/activate
            cd ~/repo
            /bin/bash ~/repo/.circleci/build.sh Singularity
            mkdir -p build && cp *.simg build
            mkdir -p build && cp Singularity* build

      # build the container!
      # You can add any other sregistry push commands here, and specify a client
      # (and make sure your define the encrypted environment credentials in circle ci
      # to push to your storage locations of choice

      # Examples with upload to storage clients defined by sregistry
      # https://singularityhub.github.io/sregistry-cli/clients
      # Environment variables must be defined in CI encrypted secrets/settings
      # https://circleci.com/docs/2.0/env-vars/
      #- /bin/bash build.sh --uri collection/container --cli google-storage Singularity
      #- /bin/bash build.sh --uri collection/container --cli google-drive Singularity
      #- /bin/bash build.sh --uri collection/container --cli globus Singularity
      #- /bin/bash build.sh --uri collection/container --cli registry Singularity

      - store_artifacts:
          path: ~/repo/build
          destination: singularity-containers
